### ISSUE TITLE
16 進数での色指定

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/NicoKaraMaker#10]
フォントなどの色を指定する際、16 進数（#FFFFFF 等）でも指定できるようにして欲しい。

［対応状況］完了
［報告経路］ニコニコ動画コメント（http://www.nicovideo.jp/watch/sm28311188 12）

**Comment by shinta0806** [comment]
Ver 3.30 にて対応完了しました。

**Comment by RinaMorii** [comment]
開発と更新、ありがとうございます！！！、最新版をダウンロードさせていただきました！！！　

わたしたちの、Web site、にも、ぜひ、訪問ください！

http://pearl-flowers.net/index.html

Music video は、" Pearl diver  Rina "、のページにあります！
