### ISSUE TITLE
ウィンドウのサイズを変更したい

### ISSUE THREAD

**Issue by shikamura128** [shinta0806/NicoKaraMaker#107]
日々のアップデートお疲れ様です。
どんどん使いやすくなっているので、これからも応援しております。

ちょっとしたことなのですが、アプリの画面のサイズを変更出来たらなと思いました。

特に字幕スタイル適用の設定変更時に、サイズが小さいと感じることがありました。

ご検討よろしくお願いします。

**Comment by shinta0806** [comment]
ご要望ありがとうございます。検討いたします。

［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
別途、全画面表示できるようにしてほしいというリクエストもあり。

**Comment by shinta0806** [comment]
ニコカラメーカー 2 にて対応完了しました。
https://github.com/shinta0806/NicoKaraMaker2/issues/4
