### ISSUE TITLE
Mac 対応の予定はありますか？

### ISSUE THREAD

**Issue by blueset** [shinta0806/NicoKaraMaker#143]
Mac でカラオケ字幕作成ツールは少ないから、対応できたら大変嬉しいです。

**Comment by shinta0806** [comment]
残念ながら、ニコカラメーカーの Mac 対応予定はございません（そもそも開発者は Mac を持っておりません）。

Mac 上で Windows を動作させる方法があるようです。そこでニコカラメーカーも動作する可能性があります（検証しているわけではないので、実際に動作するかは不明です）。
