### ISSUE TITLE
洋楽のルビが正しく登録できない

### ISSUE THREAD

**Issue by kakushino** [shinta0806/NicoKaraMaker#154]
登録しようとする単語内に別の登録した単語が含まれると、そのルビも含んでしまうことがある。
ルビを記憶しないモードの追加を希望します。

例：
1分ぐらいでon 　[オン]　を登録
2分ぐらいでlong [ロング] を登録
3分ぐらいでlongを見ると、l　ong[ロングオン]になっている事がある。
![ruby](https://cloud.githubusercontent.com/assets/24725863/21445882/5fb226dc-c902-11e6-81ce-4519566ca503.png)

**Comment by shinta0806** [comment]
ルビを一時的に適用することは、ニコカラメーカー Ver 7.11 現在で既に可能です。
ルビを一時的に適用するためには、「適用開始時刻」「適用終了時刻」を設定します。

例えば、on の適用開始時刻を [00:00:00]、on の適用終了時刻を [02:00:00] とすることにより、0 分～2 分に登場する on にのみ「オン」とルビが振られるので、3 分に登場する long には「オン」は振られません。

ニコカラメーカーで適用開始時刻・適用終了時刻を設定するためには、ルビタブでルビを振る際、「ルビ適用時刻を手動で指定する」にチェックを入れた上で、適用時刻を指定して下さい。

【参考情報】

タイムタグ規格ルビ拡張規格仕様書
http://www2u.biglobe.ne.jp/~shinta/be/TimeTagRuby.html

ニコカラメーカー配布ファイル内にある Sample フォルダ内のファイル
ルビ読み分けの例.txt

------------------------------
［対応状況］無効
［報告経路］コンタクト
