### ISSUE TITLE
曲情報のルビをニコカラメーカー上で編集できるようにしてほしい

### ISSUE THREAD

**Issue by kakushino** [shinta0806/NicoKaraMaker#155]
曲名・アーティスト名のルビが編集できない。
ルビを登録しない場合や、読みが違う場合に編集ができない。

**Comment by shinta0806** [comment]
曲情報（曲名・アーティスト名等）のルビについて、ニコカラメーカー上での編集機能を検討します。

なお、歌詞ファイル上でルビを指定することにより、Ver 7.11 現在でも曲情報のルビを指定することは可能です。

自動で設定される曲情報は、適用開始時刻・適用終了時刻が共に [99:59:99] となっていますので、歌詞ファイル中で、適用開始時刻・適用終了時刻を [99:59:99] にしたルビを指定しておくことにより、曲情報のルビを振ることができます。

逆に、他で振ったルビを曲情報に適用したくない場合は、他のルビの適用終了時刻を [99:59:98] にして下さい。

【参考情報】

タイムタグ規格ルビ拡張規格仕様書
http://shinta.coresv.com/world/TimeTagRuby.html

ニコカラメーカー配布ファイル内にある Sample フォルダ内のファイル
ルビ読み分けの例.txt

----------
［対応状況］完了
［報告経路］コンタクト

**Comment by shinta0806** [comment]
タイトル編集機能の導入に合わせて、歌詞ファイル中のルビ情報をタイトルに適用することをやめましたので、ご要望の多かった曲名等にルビが振られてしまう問題は解消されました。

曲名等にルビを振りたい場合は、タイトル設定タブにおいて、任意の行にルビを入力して下さい。
