### ISSUE TITLE
素材動画を指定せずに、背景色の指定でプレビューや動画出力をしたい

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/NicoKaraMaker#188]
通常ニコカラの作成には素材動画と歌詞が必要ですが、先に歌詞があって素材動画がまだ無い場合に、素材動画の代わりに、ダミーの背景色を指定することにより、プレビューでワイプを確認したり、仮の動画出力ができると便利です。

現在は、背景一色のダミー動画を素材動画として指定していますが、背景と同色だと見づらい場合もあり、色が選べると便利です。

［対応状況］完了
［報告経路］コンタクト

**Comment by SysVR** [comment]
ダミーの背景色を指定した場合の動画出力にAlpha付きAVIの出力ができればいいですね。
また、動画の代わりに1枚絵でもいいかもしれないですね。

**Comment by shinta0806** [comment]
1 枚絵については、ニコカラメーカー 2 にて対応完了しました。
https://github.com/shinta0806/NicoKaraMaker2/issues/85

**Comment by shinta0806** [comment]
背景色についてもニコカラメーカー 2 にて対応完了しました。
https://github.com/shinta0806/NicoKaraMaker2/issues/114
