### ISSUE TITLE
フリーズすることがある

### ISSUE THREAD

**Issue by shinta0806** [shinta0806/NicoKaraMaker#211]
ニコカラメーカーを長時間使用していると、フリーズしていることがあります。

［対応状況］完了
［報告経路］SHINTA

**Comment by shinta0806** [comment]
（原因ぽいもの）
・プレビューでは再生位置が最後になっている時にフリーズした。
・再生後に停止ボタンをクリックしてから放置するとフリーズしなかった。
・一時停止での放置は未確認。
・位置が最後だと悪いのか、再生中というステータスが悪いのか。
（メモ）
・スクリーンセーバーが起動したが影響するのか？
・外部歌詞変更にも反応しない。

**Comment by shibacho** [comment]
今日初めて使用しましたけど、正直プレビュー周りがBuggy な印象はありましたね。
映像でなくて音声だけは流れるのでカラオケ字幕だけでも表示してくれればいいのに、って感じがしました。
プレビュー箇所でうまくいかない時にログ吐いて送信する機能があれば、協力は出来ると思うのですが

**Comment by shinta0806** [comment]
ニコカラメーカー 2 では、プレビューでは再生位置が最後のまま停止することはなくなったため、本件クローズします。
