### ISSUE TITLE
ニコカラメーカー用リズミカスクリプトがニコカラメーカーに適応されない

### ISSUE THREAD

**Issue by jiajment** [shinta0806/NicoKaraMaker#212]

**Comment by shinta0806** [comment]
ニコカラメーカー用リズミカスクリプトは現在使えません。

RhythmicaLyrics のメニューから［ファイル→出力→ルビ拡張規格でタイムタグ出力→実行］を選んで .lrc ファイルを出力することにより、そのファイルをニコカラメーカーで読み込むことができます。
