### ISSUE TITLE
DirectShow

### ISSUE THREAD

**Issue by Takayan1103** [shinta0806/NicoKaraMaker#213]
動画形式に対応した適切な DirectShow フィルターがインストールされているか確認して下さい。
追加情報：動画とカラオケ字幕を接続できませんでした：
接続に必要な中間フィルターの組み合わせが見つかりませんでした。
と出て
mp4も、AVI(非圧縮)も読み込めません。
このサイトの他の記事を参考にしたりしましたが
まったくうまくできません
再起動も
再インストールもしております。

**Comment by shinta0806** [comment]
本サイトの Q&A やヘルプに記載の方法をお試しいただいたにもかかわらず、動画を読み込めない場合は、残念ながら、現時点での解決策がありません。

将来的に新しい環境になった場合などに再度お試しいただければと思います。

**Comment by shinta0806** [comment]
改めて情報を整理しましたので、ご参考にどうぞ。
ニコカラメーカーでプレビュー・動画出力ができない場合の対処法
http://shinta0806be.ldblog.jp/archives/9969533.html
