### ISSUE TITLE
角度を指定して歌詞をつける。

### ISSUE THREAD

**Issue by RRX-JP** [shinta0806/NicoKaraMaker#220]
現在横書き(左から右)のみですが、
角度を指定して設置できるようにしてほしいです。

横書き、縦書き、任意の角度

**Comment by shinta0806** [comment]
［対応状況］移行済
［報告経路］コンタクト

ニコカラメーカー 2 にて管理します。
https://github.com/shinta0806/NicoKaraMaker2/issues/184
