### ISSUE TITLE
マルチモニタ環境でプレビュー再生中にモニタをまたいだウィンドウドラッグするとフリーズする

### ISSUE THREAD

**Issue by shibacho** [shinta0806/NicoKaraMaker#222]
環境
- OS: Windows 10 Home 64bit
- CPU: Intel Core i5 6500
- Memory: 16GB
- GPU: NVIDIA GeForce 1050 GTX Ti 4GB
- バグが発生する時の動画コーデック: 
    - ビデオストリーム:H.264/AVC 
    - オーディオストリーム:AAC LC

**Comment by shinta0806** [comment]
ニコカラメーカー 2 にて対応完了しました。
shinta0806/NicoKaraMaker2#13
