### ISSUE TITLE
プレビュー時のはみ出し警告を字幕スタイル適用編集画面に出してほしい

### ISSUE THREAD

**Issue by shibacho** [shinta0806/NicoKaraMaker#223]
プレビュー時に「○○行目の字幕が横幅からはみ出ています」と警告が出ますが、
字幕スタイル適用画面で行の数字付近に警告マークを出してもらえると、どの行の歌詞に問題があるのかわかりやすいのでは、と思いました。

現状、自分は警告メッセージをメモって、字幕スタイル適用の該当行を探して、RhythmicalLyrics に戻って作業するので、メモする手間が省けます。

**Comment by shinta0806** [comment]
［対応状況］移行済
［報告経路］コンタクト

ニコカラメーカー 2 にて管理します。
https://github.com/shinta0806/NicoKaraMaker2/issues/187
