### ISSUE TITLE
字幕スタイルの一括変更

### ISSUE THREAD

**Issue by Animehakase** [shinta0806/NicoKaraMaker#227]
現在は、複数人でのパート分け字幕でそれぞれの字幕フォントを一行ずつ指定していますが、
ミスが発生しやすくなるのと、パート分けの作成に時間がかかるので、
複数の行をまとめて同じ字幕フォントに変更できる機能がほしいです。

**Comment by shinta0806** [comment]
［対応状況］完了
［報告経路］コンタクト

ニコカラメーカー 2 にて対応完了しました。
shinta0806/NicoKaraMaker2#12
