### ISSUE TITLE
字幕スタイル自動設定のやり直し

### ISSUE THREAD

**Issue by Animehakase** [shinta0806/NicoKaraMaker#228]
字幕がはみ出る事がわかり、lrcファイルで改行するなどの修正を行って再度、同じプロジェクトで読み込むと最初のlrcファイルで自動で振られた字幕位置やページ区切りがそのままになり、
中途半端なところにページ区切りが挿入されたり、表示終了の時間が歌唱終了の時間よりも大幅に短くなることがあります。現在はプロジェクトファイルを作り直すことで回避しています。
なので、字幕スタイルをリセットというか、再度自動で設定し直すボタンがほしいです。

**Comment by shinta0806** [comment]
字幕スタイル適用タブの下側にある、
自動で区切りを挿入ボタン→自動でスタイルを設定ボタン
の順にご利用ください。
