### ISSUE TITLE
スマート水平位置調整の仕様に関するリクエスト

### ISSUE THREAD

**Issue by blueset** [shinta0806/NicoKaraMaker#232]
陰なだら応援させていただきます。Eanaと申します。

ニコカラメーカーからいろんなカラオケ字幕動画に興味を持ち始めて、その作成の仕組みをずっと気になっています。今回は、SHINTA様のニコカラメーカーからインスパイアされ、ウェブでも表示できるOpen Sourceなカラオケ字幕ツールを作ってみたいと思っております。しかし、このような字幕作成ツールについての解説が少ないため、仕組みの研究はなかなか進んでいません。

もし良ければ、ニコカラメーカーの[「スマート水平位置調整」](http://shinta.coresv.com/help/NicoKaraMaker_JPN.html#LayoutTab)の具体的な仕様をご教示して頂ければ幸いです。

Issue Trackerにお邪魔しましてすみませんでした。  
拙い日本語ですが、失礼いたします。

**Comment by shinta0806** [comment]
リンクを張って頂いた先の記述が仕様となります。
よろしくお願いします。
