### ISSUE TITLE
行の途中で歌詞の色を変更したい

### ISSUE THREAD

**Issue by shikamura128** [shinta0806/NicoKaraMaker#81]
こちらのアプリにはパソカラを作成している一人として大変期待しています。

表題の通りになるのですが、行の途中でもフォントの色を変更できるようにしていただければ大変うれしいです。

コーラスで実現されている感じで、（）を利用していないときでも色を変更できればと思います。

**Comment by shinta0806** [comment]
既に、行の途中でのフォント設定は変更可能です。

歌詞ファイル上は行を分けた上で、字幕スタイル適用タブで、字幕位置を「前行追随」にしてください。

ちなみに、コーラス自動色分けは、（）内を自動的に行分割したうえで、「前行追随」を適用しており、内部的には同じ仕組みで実現しています。コーラス自動色分けされた場合の字幕スタイル適用タブを詳しく見て頂くと、参考になる部分があるかもしれません。

［対応状況］無効
［報告経路］コンタクト

**Comment by shinta0806** [comment]
行の途中でフォントを変更する方法について、ヘルプにも記載しました。
http://www2u.biglobe.ne.jp/~shinta/help/NicoKaraMaker_JPN.html#IchigyononakadeFukusunoFontsetteiwoTekiyousuru
