### ISSUE TITLE
プレビュー画面を他のタブと同時に表示できるようにしてほしい

### ISSUE THREAD

**Issue by shikamura128** [shinta0806/NicoKaraMaker#90]
プレビュー画面の下とかに「字幕フォント」「字幕位置」「字幕スタイル」が同じ画面にできるオプションがあったら便利かなと思いました。

常に上にプレビューがあって、下にタブか何かで字幕関係の設定を切り替えれて、設定を弄ったらすぐに同一画面のプレビュー画面に反映されるようなイメージです。

**Comment by shinta0806** [comment]
ご意見ありがとうございます。検討します。

［対応状況］移行済
［報告経路］コンタクト

**Comment by shinta0806** [comment]
ニコカラメーカー 2 にて管理します。
https://github.com/shinta0806/NicoKaraMaker2/issues/163
